chore: update to vitest 2.x (#2031)
## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [`status: accepting
prs`](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [X] Steps in
[CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/TypeStat/blob/main/.github/CONTRIBUTING.md)
were taken

## Overview

Cherry-pick the vitest/coverage-v8 version 2.x update onto the vitest
2.x update branch. This fixes the error:
```
 ⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
TypeError: this.resolveReporters is not a function
 ❯ V8CoverageProvider.initialize node_modules/.pnpm/@vitest+coverage-v8@1.6.0_vitest@2.1.6_@types+node@22.10.0_/node_modules/@vitest/coverage-v8/dist/provider.js:2233:22
 ❯ Vitest.initCoverageProvider node_modules/.pnpm/vitest@2.1.6_@types+node@22.10.0/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:10567:35
 ❯ Vitest.start node_modules/.pnpm/vitest@2.1.6_@types+node@22.10.0/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:10642:7
 ❯ startVitest node_modules/.pnpm/vitest@2.1.6_@types+node@22.10.0/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:11828:7
 ❯ start node_modules/.pnpm/vitest@2.1.6_@types+node@22.10.0/node_modules/vitest/dist/chunks/cac.DPEe9SCx.js:1506:17
 ❯ CAC.run node_modules/.pnpm/vitest@2.1.6_@types+node@22.10.0/node_modules/vitest/dist/chunks/cac.DPEe9SCx.js:1486:3
```
when I run `pnpm run test --coverage` locally.

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Josh Goldberg <git@joshuakgoldberg.com>